# Generated by Django 5.2.4 on 2025-07-23 06:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts_app', '0003_remove_downloadedvideo_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Combined Video', max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('thumbnail_path', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_shorts', models.ManyToManyField(related_name='combinations', to='shorts_app.generatedshort')),
            ],
        ),
    ]
