# Generated by Django 5.2.4 on 2025-07-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts_app', '0004_combinedvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CombinedVideo',
        ),
    ]
