# Generated by Django 5.2.4 on 2025-07-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts_app', '0006_videoproject_generatedprojectvideo_videoclip'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videoclip',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='videoclip',
            name='project',
        ),
        migrations.DeleteModel(
            name='GeneratedProjectVideo',
        ),
        migrations.DeleteModel(
            name='VideoClip',
        ),
        migrations.DeleteModel(
            name='VideoProject',
        ),
    ]
